# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '1bd39d83-da0e-4ff1-a20d-8f069e8d1d13'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'psrg'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'ARM_Template/azuredeploy.json'
    overrideParameters: '-projectName ARM_Template -linkedTemplateUri https://github.com/vallabha27/ARM_Template/blob/Master/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
    

